# Generated by Django 6.0.5 on 2026-05-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
