# Generated by Django 6.0.5 on 2026-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
